#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# pkg/bauen.sh — aus dem festgenagelten Osum-Stand PAKETE machen.
#
# WAS HIER ZU EINEM PAKET WIRD, und woher es kommt. Osums Runde K15 legt
# je Programm ein Buendel an: `assets/apps/<name>.prog/` mit INFO
# (Anzeigename, Beschreibung, Schluesselwoerter), `symbol.txt` und
# `daten/`. `vendor/osum/hole-osum.sh` holt beides aus DEMSELBEN
# festgenagelten Commit — die Programme nach `vendor/osum/bin/`, die
# Buendeldaten nach `vendor/osum/apps/`.
#
# Dieses Skript setzt sie zusammen:
#
#     vendor/osum/apps/<name>.prog/INFO       Anzeigename, keys, fassung
#     vendor/osum/apps/<name>.prog/start.txt  WELCHES Programm `start` ist
#     vendor/osum/bin/<programm>              die ausfuehrbare Datei
#            |
#            +-> build/pakete/<name>.opk
#
# DER ANZEIGENAME WIRD NICHT ABGESCHRIEBEN. Er steht in Osums INFO, und
# er wird von dort gelesen — dieselbe Regel, die Osum selbst aufstellt
# („eine Beschriftung, die einkompiliert ist, laesst sich nicht
# austauschen"). Ein Rezept in `pkg/rezepte/` waere die zweite Stelle,
# an der derselbe Name steht, und die zweite Stelle ist immer die, die
# irgendwann nicht mehr stimmt. Deshalb entstehen die Rezepte HIER, beim
# Bauen, und werden nicht eingecheckt.
#
#   ./pkg/bauen.sh                 alle Buendel als Pakete + Quelle
#   ./pkg/bauen.sh --ohne-quelle   nur die Pakete
set -euo pipefail
cd "$(dirname "$0")/.."

AUS=build/pakete
QUELLE=build/quelle
SCHLUESSEL=build/schluessel
MIT_QUELLE=1
[[ ${1:-} == --ohne-quelle ]] && MIT_QUELLE=0

test -d vendor/osum/apps || {
    echo "vendor/osum/apps fehlt — ./vendor/osum/hole-osum.sh laufen lassen" >&2
    exit 1; }

rm -rf "$AUS"; mkdir -p "$AUS"

# `start.txt` nennt die ausfuehrbare Datei als absoluten Pfad im
# GASTSYSTEM (`/bin/explorer`). Uebersetzt wird das hier in den Pfad im
# Baubaum — die Datei stammt aus demselben Commit.
feld() { sed 's/#.*//' "$1" | grep -m1 "^$2=" | cut -d= -f2- | sed 's/[[:space:]]*$//'; }

n=0
for d in vendor/osum/apps/*.prog; do
    [[ -d $d ]] || continue
    voll=$(basename "$d")            # explorer.prog
    name=${voll%.prog}               # explorer
    prog=$(grep -v '^#' "$d/start.txt" | grep -m1 '^/' | tr -d '[:space:]')
    datei=vendor/osum/bin/$(basename "$prog")
    if [[ ! -f $datei ]]; then
        echo "   $name uebersprungen: $prog gibt es nicht in vendor/osum/bin" >&2
        continue
    fi
    rez=$AUS/$name.rezept
    {
        echo "# Erzeugt von pkg/bauen.sh aus vendor/osum/apps/$voll."
        echo "# NICHT von Hand aendern — der Anzeigename steht in Osums INFO."
        echo "name=$name"
        echo "fassung=$(feld "$d/INFO" fassung).0.0"
        echo "titel=$(feld "$d/INFO" name)"
        echo "info=$(feld "$d/INFO" info)"
        echo "keys=$(feld "$d/INFO" keys)"
        # DIE DREI TOEPFE PLUS DIE KONSOLE. Was eine Anwendung bekommt,
        # steht im Paket und nicht in ihrem Quelltext (PACKAGING.md § 7).
        echo "handle=config"
        echo "handle=state"
        echo "handle=cache"
        echo "handle=konsole"
        echo "datei=start ../../$datei"
        echo "datei=INFO ../../$d/INFO"
        [[ -f $d/symbol ]] && echo "datei=symbol ../../$d/symbol"
        if [[ -d $d/daten ]]; then
            for f in "$d"/daten/*; do
                [[ -f $f ]] && echo "datei=daten/$(basename "$f") ../../$f"
            done
        fi
    } > "$rez"
    python3 pkg/opk.py bauen "$rez" -o "$AUS/$name.opk"
    n=$((n + 1))
done

# Von Hand geschriebene Rezepte, falls es welche gibt. Sie sind der Weg
# fuer alles, was KEIN Osum-Buendel ist.
shopt -s nullglob
for rez in pkg/rezepte/*.rezept; do
    name=$(grep -m1 '^name=' "$rez" | cut -d= -f2)
    python3 pkg/opk.py bauen "$rez" -o "$AUS/$name.opk"
    n=$((n + 1))
done
shopt -u nullglob

# ---------------------------------------------------- THE KERNEL, AS A PACKAGE
#
# Round PLAN2. The kernel of a generation is a store entry like any other
# -- same format, same hash, same collector -- and it is written here and
# not as a checked-in recipe because the ONE thing that identifies it,
# the pinned Osum commit, already lives in vendor/osum/COMMIT. A recipe in
# the repository would be a second place for that commit.
if [[ -f vendor/osum/osum.mb ]]; then
    COMMIT=$(cat vendor/osum/COMMIT)
    rez=$AUS/osum.rezept
    {
        echo "# Generated by pkg/bauen.sh. The kernel as a package."
        echo "name=osum"
        echo "fassung=1.0.0"
        echo "titel=Osum"
        echo "info=the kernel, multiboot image, pinned at ${COMMIT:0:8}"
        echo "keys=osum,kernel,kern"
        # `kind=kernel` is what `opk.py kernel` demands and what
        # `opk.py installieren` refuses: without it any application could
        # be made the kernel of a generation, and with it nothing else can.
        echo "kind=kernel"
        echo "origin=osum:$COMMIT"
        echo "datei=image ../../vendor/osum/osum.mb"
    } > "$rez"
    python3 pkg/opk.py bauen "$rez" -o "$AUS/osum.opk"
    n=$((n + 1))
fi

# ------------------------------------------- DIE ASSETS: Farbschemata und
# Hintergrundbilder.
#
# Ein Farbschema und ein Hintergrundbild sind INHALT, kein Programm --
# aber sie gehen denselben Weg: `kind=asset`, ein Store-Eintrag, ein
# Hash, derselbe signierte INDEX, derselbe Sammler. Ein zweiter
# Blob-Speicher neben dem Store waere ein zweiter Sammler, ein zweiter
# Pruefer und ein zweiter Abholweg gewesen; das ist der ganze Grund,
# warum es hier keinen gibt.
#
# Das Bild entsteht aus VIER ZEILEN TEXT (`pkg/osym.py`) -- ein Klumpen
# Oktette im Baum ist nichts, was jemand in einem Unterschied lesen kann.
shopt -s nullglob
for th in userland/themes/*.theme; do
    name=$(basename "$th" .theme)
    python3 pkg/opk.py asset-pack "$th" -o "$AUS/$name.opk" --class theme
    n=$((n + 1))
done
for wp in userland/wallpapers/*.wallpaper; do
    name=$(basename "$wp" .wallpaper)
    python3 pkg/osym.py "$wp" "$AUS/$name.osym" > /dev/null
    python3 pkg/opk.py asset-pack "$AUS/$name.osym" -o "$AUS/$name.opk" \
            --class wallpaper --name "$name"
    rm -f "$AUS/$name.osym"
    n=$((n + 1))
done
shopt -u nullglob

# ------------------------------------- ALLES UEBRIGE AUS vendor/osum/bin
#
# Bis zu dieser Runde waren genau drei der Programme je paketiert. Der
# Grund war nicht, dass die anderen schwierig sind, sondern dass jedes
# Rezept von Hand geschrieben werden musste. `pkg/recipes.py` erzeugt sie
# -- und ueberspringt, was schon ein Buendel oder ein Handrezept hat,
# damit kein Programm unter zwei Namen im Store landet.
python3 pkg/recipes.py "$AUS" > "$AUS/recipes.log"
tail -1 "$AUS/recipes.log"
shopt -s nullglob
for rez in "$AUS"/*.rezept; do
    name=$(basename "$rez" .rezept)
    [[ -f $AUS/$name.opk ]] && continue        # Buendel/Handrezept/Kernel
    python3 pkg/opk.py bauen "$rez" -o "$AUS/$name.opk" > /dev/null
    n=$((n + 1))
done
shopt -u nullglob

echo ">> $n Paket(e) in $AUS"

if [[ $MIT_QUELLE -eq 1 ]]; then
    # DER SCHLUESSEL WIRD NICHT EINGECHECKT und auch nicht wiederverwendet:
    # er entsteht bei jedem Bau neu. Fuer eine Quelle, die wirklich
    # verteilt, waere das falsch — dann muss der oeffentliche Teil fest
    # sein, sonst hat die Signatur keinen Wert. Solange die Quelle im
    # Bauverzeichnis liegt und niemand von aussen daraus installiert, ist
    # ein Schluessel je Lauf ehrlicher als einer, der im Repo liegt und
    # damit ohnehin niemandem gehoert.
    rm -rf "$QUELLE" "$SCHLUESSEL"
    mkdir -p "$QUELLE"
    python3 pkg/opk.py schluessel "$SCHLUESSEL" >/dev/null
    cp "$AUS"/*.opk "$QUELLE"/
    python3 pkg/opk.py quelle "$QUELLE" --schluessel "$SCHLUESSEL/geheim.key"
fi
